#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-azure_core
Version  : 1.23.1
Release  : 8
URL      : https://files.pythonhosted.org/packages/20/d3/4d3cab5bba6ed016c5a411348a3d01fa0f1a4e48eb9ff9b8e2d51ef79901/azure-core-1.23.1.zip
Source0  : https://files.pythonhosted.org/packages/20/d3/4d3cab5bba6ed016c5a411348a3d01fa0f1a4e48eb9ff9b8e2d51ef79901/azure-core-1.23.1.zip
Summary  : Microsoft Azure Core Library for Python
Group    : Development/Tools
License  : MIT
Requires: pypi-azure_core-license = %{version}-%{release}
Requires: pypi-azure_core-python = %{version}-%{release}
Requires: pypi-azure_core-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(requests)
BuildRequires : pypi(six)
BuildRequires : pypi(typing_extensions)

%description
# Azure Core shared client library for Python
        
        Azure core provides shared exceptions and modules for Python SDK client libraries.

%package license
Summary: license components for the pypi-azure_core package.
Group: Default

%description license
license components for the pypi-azure_core package.


%package python
Summary: python components for the pypi-azure_core package.
Group: Default
Requires: pypi-azure_core-python3 = %{version}-%{release}

%description python
python components for the pypi-azure_core package.


%package python3
Summary: python3 components for the pypi-azure_core package.
Group: Default
Requires: python3-core
Provides: pypi(azure_core)
Requires: pypi(requests)
Requires: pypi(six)
Requires: pypi(typing_extensions)

%description python3
python3 components for the pypi-azure_core package.


%prep
%setup -q -n azure-core-1.23.1
cd %{_builddir}/azure-core-1.23.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1649715223
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-azure_core
cp %{_builddir}/azure-core-1.23.1/LICENSE %{buildroot}/usr/share/package-licenses/pypi-azure_core/5d941660d20397d61e58adb87e2dd05fa60828ef
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-azure_core/5d941660d20397d61e58adb87e2dd05fa60828ef

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
